function randomGreeting() {
 const greeting = [
        "You looking great today!",
        "Have a good day!",
        "You are in a good form.",
        "I wish i had a day like you.",
        'heyo  :tr:'
    ];
    number15 = greeting[Math.floor(Math.random() * greeting.length)];
        
    //print the images generated by a random number
    document.getElementById("greeting").innerHTML = number15
    
    console.log('Output :', number15)
   
} 
// const texts = ['Oh Noo!!', 'You lost!', 'Try a next time!!'];;
// text = texts[Math.floor(Math.random() * texts.length)];
// // console.log(text)
// function randomGreeting() {
//     const texts = ['Oh Noo!!', 'You lost!', 'Try a next time!!'];;
//     text = texts[Math.floor(Math.random() * texts.length)];
//     document.getElementById("greeting").innerHTML = text
// } 